### ISSUE TITLE
Trouble making app tarball

### ISSUE THREAD

**Issue by KatharineME** [comonicon/Comonicon.jl#151] opened 2021-11-23 23:44 UTC
Hello, I am trying to create an app tarball from a simple Comonicon project and keep getting the following error. Any ideas of what could be going wrong?

```julia
julia --project deps/build.jl app tarball                     16:27:42
[ Info: building application
┌ Info: application options: 
└   options.application = ComoniconOptions.Application("build", ComoniconOptions.Asset[], false, false, "generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)", ComoniconOptions.Precompile(["test/runtests.jl"], String[]), nothing)
┌ Warning: Project has a build script, this might indicate that it is not relocatable
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/ghAiI/src/PackageCompiler.jl:744
[ Info: PackageCompiler: creating base system image (incremental=false)...
[ Info: PackageCompiler: creating system image object file, this might take a while...
Precompiling project...
  33 dependencies successfully precompiled in 15 seconds
[ Info: PackageCompiler: Executing /Users/kate/Downloads/testci/test/runtests.jl => /var/folders/z_/r2n_rt396917fl9qm_t5h7jm0000gn/T/jl_packagecompiler_ZP3qEB/jl_bPUcNp
cmd1: arg=stringoption=Sam
[ Info: PackageCompiler: Done
[ Info: PackageCompiler: creating system image object file, this might take a while...
[ Info: generating completion scripts
[ Info: creating path: /Users/kate/Downloads/testci/build/testci/completions
ERROR: LoadError: UndefVarError: Comonicon not defined
Stacktrace:
 [1] tarball_name(m::Module, name::String; application::Bool)
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/bJXHb/src/build.jl:181
 [2] build_tarball_app(m::Module, options::ComoniconOptions.Comonicon)
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/bJXHb/src/build.jl:100
 [3] install(m::Module, options::ComoniconOptions.Comonicon)
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/bJXHb/src/install.jl:68
 [4] install(m::Module; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/bJXHb/src/install.jl:3
 [5] install
   @ ~/.julia/packages/ComoniconBuilder/bJXHb/src/install.jl:2 [inlined]
 [6] #comonicon_install#3
   @ ~/.julia/packages/Comonicon/9x3SY/src/cast.jl:213 [inlined]
 [7] comonicon_install()
   @ testci ~/.julia/packages/Comonicon/9x3SY/src/cast.jl:213
 [8] top-level scope
   @ ~/Downloads/testci/deps/build.jl:1
in expression starting at /Users/kate/Downloads/testci/deps/build.jl:1
~/Downloads/testci                                                               16:34:12
```

I ran this on a test app I created with  the following structure:

```sh
.
├── Comonicon.toml
├── Manifest.toml
├── Project.toml
├── build
│   └── testci
├── deps
│   └── build.jl
├── src
│   └── testci.jl
└── test
    └── runtests.jl
```

where Comonicon.toml has the following:
```
name = "testci"

[sysimg]
filter_stdlibs=false
incremental=false

[sysimg.precompile]
execution_file = ["test/runtests.jl"]

[application]
filter_stdlibs=false
incremental=false

[application.precompile]
execution_file = ["test/runtests.jl"]
```

testci.jl has:
```julia
module testci

using Comonicon

@cast mycmd1(arg; option="Sam") = println("cmd1: arg=", arg, "option=", option)
@cast mycmd2(arg; option="Sam") = println("cmd2: arg=", arg, "option=", option)

"""
testci
"""
@main

end # module
```

and build.jl has:
```julia
using testci; testci.comonicon_install()
```

Output of versioninfo()
```Julia
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by Roger-luo** [comment] 2021-12-02 03:01
this should be fixed on latest release now

**Closed by Roger-luo** 2021-12-02 03:01 UTC

**Comment by KatharineME** [comment] 2021-12-10 21:51
Hi @Roger-luo, just getting back to this. 

I got the latest release of Comonicon and called `julia --project deps/build.jl app tarball` and this time `gsea-application-0.1.0-julia-1.7.0-darwin-x86_64.tar.gz` was made! However when I tested the `gsea` binary in the tarball, I got the error below when Julia isn't installed. So its not really relocatable yet. And just to note, when Julia is installed the `gsea` exectuable produces the same warnings as below but works.

Could I being doing something wrong?

Many thanks for your help again.


```sh
┌ Warning: Error requiring `Mux` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have JSON in its dependencies:
│    - If you have WebIO checked out for development and have
│      added JSON as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ ~/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:104
│      [5] (::WebIO.var"#75#87")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [6] err(f::Any, listener::Module, modname::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:47
│      [7] (::WebIO.var"#74#86")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [8] withpath(f::Any, path::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:37
│      [9] (::WebIO.var"#73#85")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│     [10] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:20
│     [11] __init__()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kate/.julia/packages/WebIO/Y7bGU/src/providers/mux.jl:1
└ @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:49
┌ Warning: Error requiring `WebSockets` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have Sockets in its dependencies:
│    - If you have WebIO checked out for development and have
│      added Sockets as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ ~/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:122
│      [5] (::WebIO.var"#84#96")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [6] err(f::Any, listener::Module, modname::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:47
│      [7] (::WebIO.var"#83#95")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│      [8] withpath(f::Any, path::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:37
│      [9] (::WebIO.var"#82#94")()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│     [10] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:20
│     [11] __init__()
│        @ WebIO ~/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kate/.julia/packages/WebIO/Y7bGU/src/providers/generic_http.jl:1
└ @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:49
fatal: error thrown and no exception handler available.
InitError(mod=:Blink, error=AssertionError(msg="isfile(f)"))
YY.26_60832.clone_1.clone at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib (unknown line)
jfptr_YY.26_60833.clone_1 at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
__init___60851.clone_1.clone at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib (unknown line)
jfptr___init___60852.clone_1 at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_module_run_initializer at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_finish_julia_init at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
julia_init at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_init at /Users/kate/craft/tool/GSEA.jl/build/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
main at /Users/kate/craft/tool/GSEA.jl/build/./gsea/bin/gsea (unknown line)
```

**Comment by Roger-luo** [comment] 2021-12-10 22:12
I don't think you can have anything depends on Requires that needs to be loaded after the module is loaded since it's dynamic I'm not sure what's the best to remove Requires but I think you may want to try to reproduce this error with PackageCompiler since this is mainly a static compile issue I believe and doesn't seem to be an issue in Comonicon (otherwise you should be able to do it without warnings from Mux)

**Comment by Roger-luo** [comment] 2021-12-10 22:13
So my suggestion is still to try to reproduce the error with PackageCompiler first to see if you can get rid of the dynamic parts.

**Comment by KatharineME** [comment] 2021-12-10 22:26
Sounds good, I'm trying it now. Thanks @Roger-luo.

**Comment by KatharineME** [comment] 2021-12-11 19:48
@Roger-luo I was able to duplicate the error with PackageCompiler, so now working on debugging that.
